# Generated by Django 3.1.7 on 2021-03-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('mobile', models.IntegerField()),
                ('roll', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
    ]
