# Generated by Django 3.1.7 on 2021-03-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('Menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='roll',
            new_name='Roll',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owner.user')),
                ('Menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.menu')),
            ],
        ),
    ]
