# Generated by Django 3.1.7 on 2021-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20210325_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Type',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
