# Generated by Django 3.1.7 on 2021-03-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20210326_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.menu'),
        ),
    ]
