# Generated by Django 3.1.7 on 2021-03-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20210326_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.user'),
        ),
    ]
