# Generated by Django 3.1.6 on 2021-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_auto_20210412_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
