# Generated by Django 3.1.6 on 2021-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Pay_categoery',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Due', 'Due')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Paid',
            field=models.BooleanField(default=0),
        ),
    ]
