# Generated by Django 3.1.7 on 2021-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_auto_20210414_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Thali', 'Thali'), ('snacks', 'snacks')], max_length=50, null=True),
        ),
    ]
