# Generated by Django 3.1.7 on 2021-04-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0021_auto_20210424_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('Time', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Both', 'Both')], max_length=50, null=True)),
                ('Day', models.CharField(choices=[('Today', 'Today'), ('More', 'More')], max_length=50, null=True)),
                ('Member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.user')),
            ],
        ),
    ]
