# Generated by Django 3.1.7 on 2021-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_notcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='notcome',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
