# Generated by Django 3.1.7 on 2021-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_auto_20210507_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Menu_id',
            new_name='Menu1_id',
        ),
    ]
