# Generated by Django 3.1.7 on 2021-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0023_notcome_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notcome',
            name='Ending_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notcome',
            name='Starting_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
