# Generated by Django 3.1.7 on 2021-05-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='absent',
            name='last_name',
        ),
    ]
