# Generated by Django 3.1.7 on 2021-05-12 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0025_auto_20210511_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
