# Generated by Django 3.1.7 on 2021-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0025_auto_20210428_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notcome',
            name='Date',
        ),
        migrations.AddField(
            model_name='notcome',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
