# Generated by Django 3.1.7 on 2021-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0026_auto_20210428_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notcome',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
