# Generated by Django 3.1.7 on 2021-05-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0026_auto_20210512_1050'),
        ('owner', '0026_auto_20210512_1309'),
    ]

    operations = [
    ]
