# Generated by Django 3.1.7 on 2021-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0027_merge_20210513_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date_added',
            new_name='Date_added',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_added',
            new_name='Date_added',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Amount',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
