# Generated by Django 3.1.7 on 2021-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0027_auto_20210428_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notcome',
            old_name='date',
            new_name='From',
        ),
        migrations.AddField(
            model_name='notcome',
            name='To',
            field=models.DateField(null=True),
        ),
    ]
