# Generated by Django 3.1.7 on 2021-04-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0029_auto_20210428_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notcome',
            new_name='Absent',
        ),
    ]
