# Generated by Django 3.1.7 on 2021-04-28 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0030_auto_20210428_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='From_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
